### ISSUE TITLE
Need to have Fn::Join in YAML for CodeBuildProjects and CodePipelines

### ISSUE THREAD

**Issue by maplion** [galaxy4public/aws-cloudformation-badges#3]
I am running my resources using the Serverless Framework and it gets mad at the YAML example of CodeBuildProjects and CodePipelines as written because it expects a simple string.  As such, I added in a Join to make this work:

```yaml
  Badges:
      Type: AWS::CloudFormation::Stack
      Properties:
        TemplateURL: 'https://<bucket name>.s3.<region>.amazonaws.com/badges.template'
        Parameters:
          CodeBuildProjects:
            Fn::Join:
            - ""
            - - project1
              - project2
              - project3
              - project4
          CodePipelines:
            Fn::Join:
            - ""            
            - - pipeline1
              - pipeline2
              - pipeline3
        TimeoutInMinutes: 15
```
